#!/usr/bin/env python3
"""
===============================================================================
Vibration Dosimeter Post-Processing & Analysis Utility
Standards: ISO 5349-1 (HAV) | ISO 2631-1 (WBV) | ISO 8041
===============================================================================

This script reads a `dosimeter.csv` log file generated by the Main Unit,
calculates essential daily vibration exposure metrics:
  - 8-hour equivalent daily exposure A(8) for HAV and WBV
  - Vibration Dose Value (VDV) using 4th-power accumulation
  - Estimated VDV (eVDV)
  - Time-to-EAV and Time-to-ELV exposure action/limit predictions
  - ISO safety threshold compliance evaluation (EAV & ELV)

Usage:
  python util/calc_dosimeter.py [path_to_dosimeter.csv] [--output report.txt]

Default input path: f:\\dosimeter.csv (or ./dosimeter.csv if not found)
"""

import sys
import os
import csv
import math
import argparse
from datetime import datetime

# =============================================================================
# CONSTANTS & SAFETY THRESHOLDS (ISO 5349-1, ISO 2631-1, EU Directive 2002/44/EC)
# =============================================================================
T_8H_SEC = 28800.0  # 8 hours in seconds (8 * 3600)

# Multipliers for seated Whole-Body Vibration (ISO 2631-1 section 6.1)
KX_WBV = 1.4  # X-axis multiplier for WBV health evaluation
KY_WBV = 1.4  # Y-axis multiplier for WBV health evaluation
KZ_WBV = 1.0  # Z-axis multiplier for WBV health evaluation

# Hand-Arm Vibration (HAV) Thresholds (ISO 5349-1)
HAV_EAV_A8 = 2.50   # Exposure Action Value [m/s²]
HAV_ELV_A8 = 5.00   # Exposure Limit Value  [m/s²]

# Whole-Body Vibration (WBV) Thresholds (ISO 2631-1)
WBV_EAV_A8 = 0.50   # Exposure Action Value [m/s²]
WBV_ELV_A8 = 1.15   # Exposure Limit Value  [m/s²]

WBV_EAV_VDV = 9.10   # VDV Exposure Action Value [m/s^1.75]
WBV_ELV_VDV = 21.00  # VDV Exposure Limit Value  [m/s^1.75]


def parse_dosimeter_csv(file_path):
    """
    Parse dosimeter CSV file into structured lists.
    
    Expected CSV columns:
    timestamp, ahwx, ahwy, ahwz, ahv, awx, awy, awz, av
    """
    records = []
    
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"CSV file not found: {file_path}")

    with open(file_path, mode='r', encoding='utf-8') as f:
        reader = csv.reader(f)
        header = None

        for row_idx, row in enumerate(reader):
            if not row or len(row) == 0:
                continue

            # Strip whitespace
            row = [item.strip() for item in row]

            # Check header
            if header is None:
                if 'timestamp' in row[0].lower() or 'ahwx' in [x.lower() for x in row]:
                    header = [x.lower() for x in row]
                    continue
                else:
                    # No header line, assume default column layout
                    header = ['timestamp', 'ahwx', 'ahwy', 'ahwz', 'ahv', 'awx', 'awy', 'awz', 'av']

            if len(row) < 9:
                continue

            try:
                ts_str = row[0]
                ahwx = float(row[1])
                ahwy = float(row[2])
                ahwz = float(row[3])
                ahv  = float(row[4])
                awx  = float(row[5])
                awy  = float(row[6])
                awz  = float(row[7])
                av   = float(row[8])

                records.append({
                    'timestamp': ts_str,
                    'ahwx': ahwx, 'ahwy': ahwy, 'ahwz': ahwz, 'ahv': ahv,
                    'awx': awx,  'awy': awy,  'awz': awz,  'av': av
                })
            except ValueError:
                # Skip unparseable rows
                continue

    if not records:
        raise ValueError("No valid measurement records found in CSV file.")

    return records


def calculate_metrics(records):
    """
    Calculate HAV and WBV essential metrics according to ISO standards.
    """
    N = len(records)
    dt = 1.0  # 1 Hz sampling period = 1 second per record
    T_total_sec = N * dt

    # -------------------------------------------------------------------------
    # 1. HAND-ARM VIBRATION (HAV) METRICS (ISO 5349-1)
    # -------------------------------------------------------------------------
    sum_sq_ahwx = sum(r['ahwx'] ** 2 for r in records)
    sum_sq_ahwy = sum(r['ahwy'] ** 2 for r in records)
    sum_sq_ahwz = sum(r['ahwz'] ** 2 for r in records)
    sum_sq_ahv  = sum(r['ahv'] ** 2  for r in records)

    # Equivalent RMS acceleration per axis and vector total
    ahwx_eq = math.sqrt(sum_sq_ahwx / N)
    ahwy_eq = math.sqrt(sum_sq_ahwy / N)
    ahwz_eq = math.sqrt(sum_sq_ahwz / N)
    ahv_eq  = math.sqrt(sum_sq_ahv / N)

    # 8-hour equivalent daily exposure A_HAV(8) based on vector total ahv
    # A_HAV(8) = ahv_eq * sqrt(T_total / 28800)
    A8_hav = ahv_eq * math.sqrt(T_total_sec / T_8H_SEC)

    # Per-axis A(8) for HAV
    A8_hav_x = ahwx_eq * math.sqrt(T_total_sec / T_8H_SEC)
    A8_hav_y = ahwy_eq * math.sqrt(T_total_sec / T_8H_SEC)
    A8_hav_z = ahwz_eq * math.sqrt(T_total_sec / T_8H_SEC)

    # Time allowed before reaching EAV and ELV (for current average intensity ahv_eq)
    # T_allowed = 28800 * (Limit / ahv_eq)^2
    t_eav_hav_sec = T_8H_SEC * ((HAV_EAV_A8 / ahv_eq) ** 2) if ahv_eq > 0 else float('inf')
    t_elv_hav_sec = T_8H_SEC * ((HAV_ELV_A8 / ahv_eq) ** 2) if ahv_eq > 0 else float('inf')

    # -------------------------------------------------------------------------
    # 2. WHOLE-BODY VIBRATION (WBV) METRICS (ISO 2631-1)
    # -------------------------------------------------------------------------
    sum_sq_awx = sum(r['awx'] ** 2 for r in records)
    sum_sq_awy = sum(r['awy'] ** 2 for r in records)
    sum_sq_awz = sum(r['awz'] ** 2 for r in records)
    sum_sq_av  = sum(r['av'] ** 2  for r in records)

    # Equivalent RMS acceleration per axis
    awx_eq = math.sqrt(sum_sq_awx / N)
    awy_eq = math.sqrt(sum_sq_awy / N)
    awz_eq = math.sqrt(sum_sq_awz / N)
    av_eq  = math.sqrt(sum_sq_av / N)

    # Direction-weighted RMS (kx=1.4, ky=1.4, kz=1.0)
    awx_weighted_eq = KX_WBV * awx_eq
    awy_weighted_eq = KY_WBV * awy_eq
    awz_weighted_eq = KZ_WBV * awz_eq

    # Per-axis A(8) for WBV
    A8_wbv_x = awx_weighted_eq * math.sqrt(T_total_sec / T_8H_SEC)
    A8_wbv_y = awy_weighted_eq * math.sqrt(T_total_sec / T_8H_SEC)
    A8_wbv_z = awz_weighted_eq * math.sqrt(T_total_sec / T_8H_SEC)

    # ISO 2631-1 Dominant axis A_WBV(8) = max(A8_x, A8_y, A8_z)
    A8_wbv_max = max(A8_wbv_x, A8_wbv_y, A8_wbv_z)
    dominant_axis = 'X' if A8_wbv_max == A8_wbv_x else ('Y' if A8_wbv_max == A8_wbv_y else 'Z')
    max_weighted_rms = max(awx_weighted_eq, awy_weighted_eq, awz_weighted_eq)

    # Vector total A_v(8) for WBV
    A8_wbv_vector = av_eq * math.sqrt(T_total_sec / T_8H_SEC)

    # 4th Power Vibration Dose Value (VDV) per axis (ISO 2631-1 / ISO 8041)
    # VDV_axis = k_axis * ( sum( a_w_i^4 * dt ) ) ^ (0.25)
    sum_4th_awx = sum(r['awx'] ** 4 for r in records)
    sum_4th_awy = sum(r['awy'] ** 4 for r in records)
    sum_4th_awz = sum(r['awz'] ** 4 for r in records)

    vdv_x = KX_WBV * (sum_4th_awx * dt) ** 0.25
    vdv_y = KY_WBV * (sum_4th_awy * dt) ** 0.25
    vdv_z = KZ_WBV * (sum_4th_awz * dt) ** 0.25

    # Total combined VDV = ( VDV_x^4 + VDV_y^4 + VDV_z^4 ) ^ (0.25)
    vdv_total = (vdv_x**4 + vdv_y**4 + vdv_z**4) ** 0.25

    # Estimated VDV (eVDV) = 1.4 * av_eq * (T_total_sec ^ 0.25)
    evdv = 1.4 * av_eq * (T_total_sec ** 0.25)

    # Time allowed before reaching WBV EAV and ELV (for dominant axis weighted RMS)
    t_eav_wbv_sec = T_8H_SEC * ((WBV_EAV_A8 / max_weighted_rms) ** 2) if max_weighted_rms > 0 else float('inf')
    t_elv_wbv_sec = T_8H_SEC * ((WBV_ELV_A8 / max_weighted_rms) ** 2) if max_weighted_rms > 0 else float('inf')

    return {
        'N': N,
        'T_total_sec': T_total_sec,
        # HAV
        'ahwx_eq': ahwx_eq, 'ahwy_eq': ahwy_eq, 'ahwz_eq': ahwz_eq, 'ahv_eq': ahv_eq,
        'A8_hav': A8_hav, 'A8_hav_x': A8_hav_x, 'A8_hav_y': A8_hav_y, 'A8_hav_z': A8_hav_z,
        't_eav_hav_sec': t_eav_hav_sec, 't_elv_hav_sec': t_elv_hav_sec,
        # WBV
        'awx_eq': awx_eq, 'awy_eq': awy_eq, 'awz_eq': awz_eq, 'av_eq': av_eq,
        'awx_weighted_eq': awx_weighted_eq, 'awy_weighted_eq': awy_weighted_eq, 'awz_weighted_eq': awz_weighted_eq,
        'A8_wbv_x': A8_wbv_x, 'A8_wbv_y': A8_wbv_y, 'A8_wbv_z': A8_wbv_z,
        'A8_wbv_max': A8_wbv_max, 'dominant_axis': dominant_axis, 'A8_wbv_vector': A8_wbv_vector,
        'vdv_x': vdv_x, 'vdv_y': vdv_y, 'vdv_z': vdv_z, 'vdv_total': vdv_total, 'evdv': evdv,
        't_eav_wbv_sec': t_eav_wbv_sec, 't_elv_wbv_sec': t_elv_wbv_sec
    }


def format_duration(seconds):
    """Format seconds into HH:MM:SS or 'inf'."""
    if math.isinf(seconds) or seconds > 86400 * 365:
        return "N/A (> 1 year)"
    hrs = int(seconds // 3600)
    mins = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    return f"{hrs:02d}h {mins:02d}m {secs:02d}s"


def generate_report(file_path, m):
    """Generate printable ASCII report."""
    dur_str = format_duration(m['T_total_sec'])

    # HAV Status
    hav_status = "OK (SAFE)"
    if m['A8_hav'] >= HAV_ELV_A8:
        hav_status = "DANGER (EXCEEDS ELV 5.0 m/s²)"
    elif m['A8_hav'] >= HAV_EAV_A8:
        hav_status = "WARNING (EXCEEDS EAV 2.5 m/s²)"

    # WBV Status
    wbv_status = "OK (SAFE)"
    if m['A8_wbv_max'] >= WBV_ELV_A8 or m['vdv_total'] >= WBV_ELV_VDV:
        wbv_status = "DANGER (EXCEEDS ELV 1.15 m/s² / 21 VDV)"
    elif m['A8_wbv_max'] >= WBV_EAV_A8 or m['vdv_total'] >= WBV_EAV_VDV:
        wbv_status = "WARNING (EXCEEDS EAV 0.50 m/s² / 9.1 VDV)"

    lines = []
    lines.append("===============================================================================")
    lines.append("               VIBRATION DOSIMETER ANALYSIS REPORT")
    lines.append("               Standards: ISO 5349-1 (HAV) | ISO 2631-1 (WBV)")
    lines.append("===============================================================================")
    lines.append(f"Input Log File   : {file_path}")
    lines.append(f"Total Logged Time: {dur_str} ({m['N']} seconds / {m['N']} samples @ 1 Hz)")
    lines.append(f"Report Generated : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("-------------------------------------------------------------------------------")
    lines.append("")

    # HAV SECTION
    lines.append("1. HAND-ARM VIBRATION (HAV) ANALYSIS (ISO 5349-1)")
    lines.append("-------------------------------------------------------------------------------")
    lines.append(f"  * RMS Acceleration (Equiv):")
    lines.append(f"      ahwx_eq = {m['ahwx_eq']:.4f} m/s² | ahwy_eq = {m['ahwy_eq']:.4f} m/s² | ahwz_eq = {m['ahwz_eq']:.4f} m/s²")
    lines.append(f"      ahv_eq  (Vector Total) = {m['ahv_eq']:.4f} m/s²")
    lines.append(f"  * 8-Hour Daily Exposure A_HAV(8):")
    lines.append(f"      A_HAV(8) Vector Total  = {m['A8_hav']:.4f} m/s²")
    lines.append(f"      [Per-axis: Ax(8)={m['A8_hav_x']:.4f}, Ay(8)={m['A8_hav_y']:.4f}, Az(8)={m['A8_hav_z']:.4f}]")
    lines.append(f"  * ISO 5349-1 Safety Limits:")
    lines.append(f"      EAV Threshold (Action) = {HAV_EAV_A8:.2f} m/s² | Time allowed = {format_duration(m['t_eav_hav_sec'])}")
    lines.append(f"      ELV Threshold (Limit)  = {HAV_ELV_A8:.2f} m/s² | Time allowed = {format_duration(m['t_elv_hav_sec'])}")
    lines.append(f"  * Exposure Compliance Status: {hav_status}")
    lines.append("")

    # WBV SECTION
    lines.append("2. WHOLE-BODY VIBRATION (WBV) ANALYSIS (ISO 2631-1)")
    lines.append("-------------------------------------------------------------------------------")
    lines.append(f"  * RMS Acceleration (Unweighted Equiv):")
    lines.append(f"      awx_eq = {m['awx_eq']:.4f} m/s² | awy_eq = {m['awy_eq']:.4f} m/s² | awz_eq = {m['awz_eq']:.4f} m/s²")
    lines.append(f"  * Directional Weighted RMS (kx=1.4, ky=1.4, kz=1.0 for seated):")
    lines.append(f"      1.4*awx = {m['awx_weighted_eq']:.4f} m/s² | 1.4*awy = {m['awy_weighted_eq']:.4f} m/s² | 1.0*awz = {m['awz_weighted_eq']:.4f} m/s²")
    lines.append(f"  * 8-Hour Daily Exposure A_WBV(8):")
    lines.append(f"      A_x(8) = {m['A8_wbv_x']:.4f} m/s² | A_y(8) = {m['A8_wbv_y']:.4f} m/s² | A_z(8) = {m['A8_wbv_z']:.4f} m/s²")
    lines.append(f"      Dominant Axis A_WBV(8) = {m['A8_wbv_max']:.4f} m/s² (Axis {m['dominant_axis']})")
    lines.append(f"      Vector Total A_v(8)   = {m['A8_wbv_vector']:.4f} m/s²")
    lines.append(f"  * Vibration Dose Value (VDV) 4th-Power Method:")
    lines.append(f"      VDV_x = {m['vdv_x']:.4f} m/s^1.75 | VDV_y = {m['vdv_y']:.4f} m/s^1.75 | VDV_z = {m['vdv_z']:.4f} m/s^1.75")
    lines.append(f"      VDV Total Combined    = {m['vdv_total']:.4f} m/s^1.75")
    lines.append(f"      Estimated VDV (eVDV)  = {m['evdv']:.4f} m/s^1.75")
    lines.append(f"  * ISO 2631-1 Safety Limits:")
    lines.append(f"      A(8) EAV = {WBV_EAV_A8:.2f} m/s²  | Time allowed = {format_duration(m['t_eav_wbv_sec'])}")
    lines.append(f"      A(8) ELV = {WBV_ELV_A8:.2f} m/s²  | Time allowed = {format_duration(m['t_elv_wbv_sec'])}")
    lines.append(f"      VDV  EAV = {WBV_EAV_VDV:.1f} m/s^1.75 | VDV ELV = {WBV_ELV_VDV:.1f} m/s^1.75")
    lines.append(f"  * Exposure Compliance Status: {wbv_status}")
    lines.append("===============================================================================")

    return "\n".join(lines)


def plot_metrics(records, m, file_path, save_path=None, show_plot=True):
    """
    Generate a 4-panel ISO 5349-1 and ISO 2631-1 vibration visualization dashboard.
    """
    try:
        import matplotlib.pyplot as plt
        import numpy as np
    except ImportError:
        print("\n[WARN] matplotlib is not installed. To view visualization plots, install via: pip install matplotlib")
        return

    N = len(records)
    time_s = np.arange(N)

    # Extract series
    ahwx = np.array([r['ahwx'] for r in records])
    ahwy = np.array([r['ahwy'] for r in records])
    ahwz = np.array([r['ahwz'] for r in records])
    ahv  = np.array([r['ahv']  for r in records])

    awx  = np.array([r['awx']  for r in records])
    awy  = np.array([r['awy']  for r in records])
    awz  = np.array([r['awz']  for r in records])
    av   = np.array([r['av']   for r in records])

    # Compute cumulative metrics over time
    cum_ahv_sq = np.cumsum(ahv ** 2)
    cum_A8_hav = np.sqrt(cum_ahv_sq / T_8H_SEC)

    cum_awx_sq = np.cumsum(awx ** 2)
    cum_awy_sq = np.cumsum(awy ** 2)
    cum_awz_sq = np.cumsum(awz ** 2)
    cum_A8_wbv_x = KX_WBV * np.sqrt(cum_awx_sq / T_8H_SEC)
    cum_A8_wbv_y = KY_WBV * np.sqrt(cum_awy_sq / T_8H_SEC)
    cum_A8_wbv_z = KZ_WBV * np.sqrt(cum_awz_sq / T_8H_SEC)
    cum_A8_wbv_dom = np.maximum(cum_A8_wbv_x, np.maximum(cum_A8_wbv_y, cum_A8_wbv_z))

    cum_awx_4 = np.cumsum(awx ** 4)
    cum_awy_4 = np.cumsum(awy ** 4)
    cum_awz_4 = np.cumsum(awz ** 4)
    cum_vdv_x = KX_WBV * (cum_awx_4 ** 0.25)
    cum_vdv_y = KY_WBV * (cum_awy_4 ** 0.25)
    cum_vdv_z = KZ_WBV * (cum_awz_4 ** 0.25)
    cum_vdv_tot = (cum_vdv_x**4 + cum_vdv_y**4 + cum_vdv_z**4) ** 0.25

    fig, axs = plt.subplots(2, 2, figsize=(14, 9))
    fig.suptitle(f"Vibration Dosimeter Analysis Dashboard\nFile: {file_path} (Duration: {format_duration(m['T_total_sec'])})",
                 fontsize=14, fontweight='bold')

    # ── Panel 1: HAV Time Series (ISO 5349-1) ─────────────────────────────────
    ax1 = axs[0, 0]
    ax1.plot(time_s, ahwx, label="ahwx (X)", color="#1f77b4", alpha=0.7, lw=1.2)
    ax1.plot(time_s, ahwy, label="ahwy (Y)", color="#2ca02c", alpha=0.7, lw=1.2)
    ax1.plot(time_s, ahwz, label="ahwz (Z)", color="#ff7f0e", alpha=0.7, lw=1.2)
    ax1.plot(time_s, ahv,  label="ahv (Vector Total)", color="#d62728", lw=1.8)
    ax1.axhline(m['ahv_eq'], color="#8c564b", linestyle="--", lw=1.2,
                label=f"ahv_eq ({m['ahv_eq']:.2f} m/s²)")
    ax1.set_title("1. Hand-Arm Vibration (HAV) — 1 Hz Weighted RMS (ISO 5349-1)", fontweight='bold', fontsize=11)
    ax1.set_xlabel("Elapsed Time (seconds)")
    ax1.set_ylabel("Acceleration RMS [m/s²]")
    ax1.grid(True, linestyle=":", alpha=0.6)
    ax1.legend(loc="upper right", fontsize=8)

    # ── Panel 2: WBV Time Series (ISO 2631-1) ─────────────────────────────────
    ax2 = axs[0, 1]
    ax2.plot(time_s, awx, label="awx (X)", color="#1f77b4", alpha=0.7, lw=1.2)
    ax2.plot(time_s, awy, label="awy (Y)", color="#2ca02c", alpha=0.7, lw=1.2)
    ax2.plot(time_s, awz, label="awz (Z)", color="#ff7f0e", alpha=0.7, lw=1.2)
    ax2.plot(time_s, av,  label="av (Vector Total)", color="#9467bd", lw=1.8)
    ax2.axhline(m['av_eq'], color="#8c564b", linestyle="--", lw=1.2,
                label=f"av_eq ({m['av_eq']:.2f} m/s²)")
    ax2.set_title("2. Whole-Body Vibration (WBV) — 1 Hz Weighted RMS (ISO 2631-1)", fontweight='bold', fontsize=11)
    ax2.set_xlabel("Elapsed Time (seconds)")
    ax2.set_ylabel("Acceleration RMS [m/s²]")
    ax2.grid(True, linestyle=":", alpha=0.6)
    ax2.legend(loc="upper right", fontsize=8)

    # ── Panel 3: Progressive A(8) Exposure vs ISO Limits ──────────────────────
    ax3 = axs[1, 0]
    ax3.plot(time_s, cum_A8_hav, label="A_HAV(8) Cumulative", color="#d62728", lw=2)
    ax3.plot(time_s, cum_A8_wbv_dom, label=f"A_WBV(8) Dominant ({m['dominant_axis']})", color="#1f77b4", lw=2)

    # Threshold lines
    ax3.axhline(HAV_EAV_A8, color="#e377c2", linestyle="--", lw=1.4, label=f"HAV EAV ({HAV_EAV_A8} m/s²)")
    ax3.axhline(HAV_ELV_A8, color="#d62728", linestyle=":",  lw=1.6, label=f"HAV ELV ({HAV_ELV_A8} m/s²)")
    ax3.axhline(WBV_EAV_A8, color="#ff7f0e", linestyle="--", lw=1.4, label=f"WBV EAV ({WBV_EAV_A8} m/s²)")
    ax3.axhline(WBV_ELV_A8, color="#7f7f7f", linestyle=":",  lw=1.6, label=f"WBV ELV ({WBV_ELV_A8} m/s²)")

    ax3.set_title("3. Progressive Daily Exposure A(8) vs ISO Limits", fontweight='bold', fontsize=11)
    ax3.set_xlabel("Elapsed Time (seconds)")
    ax3.set_ylabel("A(8) Exposure [m/s²]")
    ax3.grid(True, linestyle=":", alpha=0.6)
    ax3.legend(loc="upper left", fontsize=8)

    # ── Panel 4: Progressive VDV vs ISO 2631-1 Limits ─────────────────────────
    ax4 = axs[1, 1]
    ax4.plot(time_s, cum_vdv_x,   label="VDV_x (1.4*X)", color="#1f77b4", alpha=0.7, lw=1.2)
    ax4.plot(time_s, cum_vdv_y,   label="VDV_y (1.4*Y)", color="#2ca02c", alpha=0.7, lw=1.2)
    ax4.plot(time_s, cum_vdv_z,   label="VDV_z (1.0*Z)", color="#ff7f0e", alpha=0.7, lw=1.2)
    ax4.plot(time_s, cum_vdv_tot, label="VDV Total Combined", color="#9467bd", lw=2)

    ax4.axhline(WBV_EAV_VDV, color="#d62728", linestyle="--", lw=1.4, label=f"VDV EAV ({WBV_EAV_VDV} m/s^1.75)")
    ax4.axhline(WBV_ELV_VDV, color="#8c564b", linestyle=":",  lw=1.6, label=f"VDV ELV ({WBV_ELV_VDV} m/s^1.75)")

    ax4.set_title("4. Progressive Vibration Dose Value (VDV) 4th-Power", fontweight='bold', fontsize=11)
    ax4.set_xlabel("Elapsed Time (seconds)")
    ax4.set_ylabel("VDV [m/s^1.75]")
    ax4.grid(True, linestyle=":", alpha=0.6)
    ax4.legend(loc="upper left", fontsize=8)

    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, dpi=150)
        print(f"[INFO] Plot image saved to: {save_path}")

    if show_plot:
        try:
            plt.show()
        except Exception as e:
            print(f"[WARN] Unable to display GUI window (headless environment): {e}")


def main():
    parser = argparse.ArgumentParser(description="Calculate A(8) and VDV metrics from dosimeter.csv log file.")
    parser.add_argument("file_path", nargs="?", default=None, help="Path to dosimeter.csv file (default: f:\\dosimeter.csv or ./dosimeter.csv)")
    parser.add_argument("-o", "--output", help="Optional output text file path to save the report")
    parser.add_argument("-s", "--save-plot", help="Optional path to save visualization plot as an image (e.g. dosimeter_plot.png)")
    parser.add_argument("--no-plot", action="store_true", help="Disable displaying interactive plot window")
    args = parser.parse_args()

    # Determine input path
    file_path = args.file_path
    if file_path is None:
        if os.path.exists(r"f:\dosimeter.csv"):
            file_path = r"f:\dosimeter.csv"
        elif os.path.exists("dosimeter.csv"):
            file_path = "dosimeter.csv"
        elif os.path.exists("util/dosimeter.csv"):
            file_path = "util/dosimeter.csv"
        else:
            print("Error: No dosimeter.csv file specified and default locations (f:\\dosimeter.csv, ./dosimeter.csv) do not exist.")
            sys.exit(1)

    try:
        records = parse_dosimeter_csv(file_path)
        metrics = calculate_metrics(records)
        report = generate_report(file_path, metrics)
        print(report)

        if args.output:
            with open(args.output, "w", encoding="utf-8") as f_out:
                f_out.write(report)
            print(f"\n[INFO] Report saved to: {args.output}")

        # Visualization plot
        plot_metrics(records, metrics, file_path, save_path=args.save_plot, show_plot=not args.no_plot)

    except Exception as e:
        print(f"Error processing dosimeter CSV file: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
